version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - api_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:7.0.13

  web:
    build: ./
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  nginx:
    build: ./
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  api_postgres_data: